---
title: "Marketing_empirical"
author: "Lux"
date: "2025-04-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Deskriptiva


```{r packages}
#import packages
library(tidyverse)
library(readxl)
library(dplyr)
library(ggplot2)


```


```{r data}
#read in data from excel in root directory
data <- read_excel("data.xlsx")



# filter rows where O = 8 and O = 6

#data <- data %>%
#  filter(O != 8 & O != 6) %>%
#  filter(T != 2)

```

### P deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(P = as.factor(P)) %>%
  group_by(P) %>%
  summarise(count = n())

```
### M deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(M = as.factor(M)) %>%
  group_by(M) %>%
  summarise(count = n())

```

### O deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(O = as.factor(`O`)) %>%
  group_by(O) %>%
  summarise(count = n())


# group variable P by factor and count
data %>%
  mutate(P = as.factor(`P`)) %>%
  group_by(P) %>%
  summarise(count = n())


# calculate the average of T per group in O


data %>%
  group_by(O) %>%
  summarise(mean_T = mean(T, na.rm = TRUE)) %>%
  arrange(desc(mean_T))




# group by M and O and count

data %>%
  group_by(M, O) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) 




```
### OQ deskriptiva

```{r}
data %>%
  group_by( O, Q) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```
### OR deskriptiva


```{r}
data %>%
  group_by(O, R) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```

### Q deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(Q = as.factor(`Q`)) %>%
  group_by(Q) %>%
  summarise(count = n())


```

### R deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(R = as.factor(`R`)) %>%
  group_by(R) %>%
  summarise(count = n())


```

### T deskriptiva
```{r}
# group variable P by factor and count
data %>%
  mutate(T = as.factor(`T`)) %>%
  group_by(T) %>%
  summarise(count = n())


```

### Chisq O vs Q (nije primjerencsq;mali broj kategorija 8, 6, 1)
```{r}


# Chi-squared test for independence O vs M
chisq.test(data$O, data$Q)



```

### Fisher O vs Q (mali broj opservacija u kategorijama 8, 6, 1)

```{r}
# Fisher's exact test for independence O vs M
fisher.test(data$O, data$Q)
```



### Chisq O vs R
```{r}
# Chi-squared test for independence O vs R
chisq.test(data$O, data$R)



```


### Fisher O vs R 

```{r}
# Fisher's exact test for independence O vs M
fisher.test(data$O, data$R)
```



### Chisq O vs T
```{r}
# Chi-squared test for independence O vs T
chisq.test(data$O, data$T)
```


### Fisher O vs T 

```{r}
# Fisher's exact test for independence O vs T
fisher.test(data$O, data$T)
```


### Fisher O vs P 

```{r}
# Fisher's exact test for independence O vs T
fisher.test(data$O, data$P)
```



### S deskriptiva

```{r}
# group variable S by factor and count
data %>%
  mutate(S = as.factor(S)) %>%
  group_by(S) %>%
  summarise(count = n())
```


